service: koge-api

frameworkVersion: "3"

custom:
  domain:
    dev: koge.dev.toools.space
    prd: koge.toools.space

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

  NodeEnv:
    dev: development
    prd: production

  TableName:
    dev: koge-tb-dsv
    prd: koge-tb

package:
  individually: true
  include:
    - bin/**

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'prd'}
  region: sa-east-1
  memorySize: 128
  timeout: 30
  logRetentionInDays: 1

  environment:
    NODE_ENV: ${self:custom.NodeEnv.${self:provider.stage}}

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: /
          method: GET
          cors: true

resources:
  Resources:
    KogeDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.TableName.${self:provider.stage}}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-certificate-creator
  - serverless-domain-manager
