name: koge api

on:
  push:
    branches:
      - main

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: make build

      - name: create certificate
        run: sls create-cert
      
      - name: create domain
        run: sls create_domain

      - name: Deploy
        run: make deploy