name: koge api

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set STAGE variable
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "STAGE=prd" >> $GITHUB_ENV
          else
            echo "STAGE=dev" >> $GITHUB_ENV
          fi

      - name: Print STAGE variable
        run: echo $STAGE

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: make build

      - name: create certificate
        run: sls create-cert --stage ${{ env.STAGE }}
      
      - name: create domain
        run: sls create_domain --stage ${{ env.STAGE }}

      - name: Deploy
        run: make deploy STAGE=${{ env.STAGE }}