name: koge api

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set STAGE variable
        run: |
          if [[ "${{ github.base_ref }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "STAGE=production" >> $GITHUB_ENV
          else
            echo "STAGE=development" >> $GITHUB_ENV
          fi

      - name: Print STAGE variable
        run: echo $STAGE

      - name: Build
        run: STAGE=${{ env.STAGE }} make build

      - name: Deploy
        run: STAGE=${{ env.STAGE }} make deploy